/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React from 'react';
import { RiskPrognosis } from '../types';
import { RefreshCw, BarChart2, ShieldCheck, Activity } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, ResponsiveContainer, Cell, Tooltip } from 'recharts';

interface ResultCardProps {
  result: RiskPrognosis;
  onReset: () => void;
}

export function ResultCard({ result, onReset }: ResultCardProps) {
  const chartData = result.factors.map(f => ({
    name: f.name,
    value: f.value,
    severity: f.severity
  }));

  const getBarColor = (severity: string) => {
    if (severity === 'high') return '#EF4444';
    if (severity === 'moderate') return '#F59E0B';
    return '#10B981';
  };

  return (
    <div className="space-y-10 pb-32">
      {/* Medical Disclaimer at Top */}
      <section className="bg-amber-50/50 border border-amber-100 p-6 rounded-3xl">
        <div className="flex items-start gap-3">
          <div className="mt-1">
             <ShieldCheck size={16} className="text-amber-600" />
          </div>
          <div className="space-y-2">
            <h5 className="text-[10px] font-black uppercase tracking-widest text-amber-900">Medical Disclaimer & Notice</h5>
            <p className="text-[11px] font-bold text-amber-800/80 leading-relaxed">
              This assessment is generated by an automated clinical data model and is provided for **informational reference only**. It does not constitute a formal medical diagnosis or professional clinical advice. 
            </p>
            <p className="text-[11px] font-bold text-amber-900 leading-relaxed">
              If you have any clinical concerns or symptomatic distress, please consult a qualified healthcare professional immediately. Trust your symptoms and professional medical guidance over automated software indicators.
            </p>
          </div>
        </div>
      </section>

      {/* Risk Summary Header */}
      <div className="bg-gray-900 p-8 rounded-[2.5rem] text-white shadow-2xl relative overflow-hidden">
        <div className="relative z-10 flex justify-between items-start">
          <div>
            <p className="text-[10px] font-black uppercase tracking-[0.3em] opacity-60 mb-2">Prognosis Index</p>
            <h2 className="font-serif text-6xl font-light italic leading-none">
              {result.category}
            </h2>
            <p className="mt-2 text-2xl font-sans opacity-40 tracking-tighter">
              Risk Index: 0.{result.score}
            </p>
          </div>
          <div className="flex flex-col items-end gap-2">
             <div className="h-10 w-10 rounded-full bg-white/10 flex items-center justify-center">
                <ShieldCheck className="text-green-400" size={20} />
             </div>
             <span className="text-[9px] font-black uppercase tracking-widest opacity-50">Secure</span>
          </div>
        </div>
        <p className="mt-8 text-xs leading-relaxed text-gray-400 font-medium max-w-[90%]">
          Analysis complete. Your PMOS risk assessment is securely isolated on this device. Data encrypted with AES-256 equivalent local keys.
        </p>
        <div className="absolute -bottom-12 -right-12 w-40 h-40 bg-white/5 rounded-full blur-3xl" />
      </div>

      {/* Factor Breakdown Graph */}
      <section className="bg-white border border-gray-100 p-8 rounded-[2.5rem] shadow-sm">
        <div className="flex items-center gap-2 mb-8">
          <BarChart2 size={16} className="text-gray-400" />
          <h4 className="text-[10px] font-black uppercase tracking-[0.2em] text-gray-400">Factor Breakdown</h4>
        </div>
        
        <div className="h-[240px] w-full">
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={chartData} layout="vertical" margin={{ left: -20, right: 20 }}>
              <XAxis type="number" hide domain={[0, 40]} />
              <YAxis 
                dataKey="name" 
                type="category" 
                axisLine={false} 
                tickLine={false} 
                tick={{ fontSize: 10, fontWeight: 800, fill: '#111827' }}
                width={100}
              />
              <Tooltip 
                cursor={{ fill: '#F9FAFB' }}
                contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 10px 15px -3px rgba(0,0,0,0.1)' }}
              />
              <Bar dataKey="value" radius={[0, 8, 8, 0]} barSize={24}>
                {chartData.map((entry, index) => (
                  <Cell key={`cell-${index}`} fill={getBarColor(entry.severity)} />
                ))}
              </Bar>
            </BarChart>
          </ResponsiveContainer>
        </div>
        <p className="mt-4 text-[9px] text-gray-400 font-bold uppercase tracking-widest text-center italic">
          Higher values indicate stronger risk correlation
        </p>
      </section>

      {/* Detailed Recommendations */}
      <section>
        <div className="flex items-center gap-2 mb-6 px-1">
          <Activity size={16} className="text-gray-400" />
          <h4 className="text-[10px] font-black uppercase tracking-[0.2em] text-gray-400">Detailed Recommendations</h4>
        </div>
        <div className="space-y-4">
          {result.recommendations.map((rec, i) => (
            <div key={i} className="bg-white border border-gray-100 p-6 rounded-3xl flex gap-4 shadow-sm group">
              <div className="w-1.5 h-1.5 rounded-full bg-gray-900 mt-1.5 shrink-0 transition-transform group-hover:scale-150" />
              <p className="text-[13px] font-bold text-gray-700 leading-relaxed tracking-tight">
                {rec}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Footer Actions */}
      <div className="flex flex-col gap-4 pt-4">
        <button 
          onClick={onReset}
          className="w-full bg-gray-900 text-white p-6 rounded-[2rem] font-black uppercase tracking-[0.2em] text-[11px] flex items-center justify-center gap-2 shadow-2xl active:scale-95 transition-all"
        >
          <RefreshCw size={14} strokeWidth={3} /> Re-analyze Data
        </button>
        
        <div className="bg-green-50/30 border border-green-100/30 p-5 rounded-2xl text-center">
          <p className="text-[9px] font-black uppercase tracking-widest text-green-700/60 leading-relaxed">
            🛡️ HIPAA Compliant Encryption<br/>Local-Only Analysis Complete
          </p>
        </div>
      </div>
    </div>
  );
}
